// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH2ttp8TsxsxlCCHCS3KarWoompCynho0',
    appId: '1:143853325192:web:5de756c39806f7dc58c83d',
    messagingSenderId: '143853325192',
    projectId: 'bmi-tracker-80add',
    authDomain: 'bmi-tracker-80add.firebaseapp.com',
    storageBucket: 'bmi-tracker-80add.firebasestorage.app',
    measurementId: 'G-5W6LG8SE3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOjm_8tOfyOcKLLzlT3AJNkya4blaWAFY',
    appId: '1:143853325192:android:629d3137fc7904dd58c83d',
    messagingSenderId: '143853325192',
    projectId: 'bmi-tracker-80add',
    storageBucket: 'bmi-tracker-80add.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_05RqXuG8pote3hSSAzfBTn9eP0aPpOU',
    appId: '1:143853325192:ios:865c3f18be7bc31258c83d',
    messagingSenderId: '143853325192',
    projectId: 'bmi-tracker-80add',
    storageBucket: 'bmi-tracker-80add.firebasestorage.app',
    iosBundleId: 'com.example.bmiTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_05RqXuG8pote3hSSAzfBTn9eP0aPpOU',
    appId: '1:143853325192:ios:865c3f18be7bc31258c83d',
    messagingSenderId: '143853325192',
    projectId: 'bmi-tracker-80add',
    storageBucket: 'bmi-tracker-80add.firebasestorage.app',
    iosBundleId: 'com.example.bmiTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH2ttp8TsxsxlCCHCS3KarWoompCynho0',
    appId: '1:143853325192:web:992dfe32b6e2f06058c83d',
    messagingSenderId: '143853325192',
    projectId: 'bmi-tracker-80add',
    authDomain: 'bmi-tracker-80add.firebaseapp.com',
    storageBucket: 'bmi-tracker-80add.firebasestorage.app',
    measurementId: 'G-GJ98WDMZKE',
  );
}
